@apiDomain = localhost:3001
### book-info

GET http://{{apiDomain}}/v3/books/api/info
  ?url=http://www.81ht.com/book/92542.html

### book-infos
POST http://{{apiDomain}}/v3/books/api/infos
Content-Type: application/json

["http://www.81ht.com/book/92542.html"]

### search
GET http://{{apiDomain}}/v3/books/api/search
  ?keyword=彼岸
